package view;

import controllers.FourPlayersController;
import controllers.InitialDataController;
import controllers.TwoPlayersMatchController;
import model.Exceptions.InvalidNumberOfPlayersException;

import java.awt.*;

public class ScreenToAskForInitialData extends javax.swing.JFrame {

    private static final String textFor2PlayerOption = "2 Jugadores";
    private static final String textFor4PlayerOption = "4 Jugadores";
    private static final String textFor6PlayerOption = "6 Jugadores";
    private static final int WINDOWWIDTH = 450;
    private static final int WINDOWHEIGHT = 200 ;
    private InitialDataController controller;
    int numberOfPlayers;

    public ScreenToAskForInitialData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMessage = new javax.swing.JLabel();
        askForPlayersQuantityMessage = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        playerQuantityList = new javax.swing.JComboBox<>();
        separator = new javax.swing.JSeparator();
        controller = new InitialDataController();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido A Truco");
        setName("PantallaBienvenida");
        setPreferredSize(new java.awt.Dimension(WINDOWWIDTH, WINDOWHEIGHT));
        setResizable(false);

        welcomeMessage.setFont(new java.awt.Font("Arial", Font.BOLD, 28)); // NOI18N
        welcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeMessage.setText("Bienvenido a Truco");
        welcomeMessage.setAlignmentY(0.0F);

        askForPlayersQuantityMessage.setFont(new java.awt.Font("Arial", Font.PLAIN, 14)); // NOI18N
        askForPlayersQuantityMessage.setText("Por favor, seleccione la cantidad de jugadores");

        startGameButton.setText("Comenzar Partida");
        startGameButton.addActionListener(evt -> {
            try {
                startGameButtonPressed(evt);
            } catch (InvalidNumberOfPlayersException e) {
                e.printStackTrace();
            }
        });

        playerQuantityList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Jugadores", "4 Jugadores", "6 Jugadores" }));
        playerQuantityList.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent( startGameButton )
                                .addGap(183, 183, 183))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(92, 92, 92)
                                                .addComponent( welcomeMessage ))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent( playerQuantityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent( askForPlayersQuantityMessage )
                                                        .addComponent( separator, javax.swing.GroupLayout.PREFERRED_SIZE, WINDOWWIDTH - 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                 .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent( welcomeMessage )
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent( separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent( askForPlayersQuantityMessage )
                                .addGap(18, 18, 18)
                                .addComponent( playerQuantityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent( startGameButton )
                                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startGameButtonPressed(java.awt.event.ActionEvent evt) throws InvalidNumberOfPlayersException {//GEN-FIRST:event_jButton1ActionPerformed
        String option = (String) playerQuantityList.getSelectedItem();
        switch (option){
            case textFor2PlayerOption:

                numberOfPlayers = 2;
                controller.prepareTableFor( numberOfPlayers );

                TwoPlayersGame twoPlayersGameView = new TwoPlayersGame();

                TwoPlayersMatchController twoPlayerController = new TwoPlayersMatchController(twoPlayersGameView, controller.getTable()) ;

                twoPlayersGameView.setController( twoPlayerController );

                twoPlayerController.drawCardsPlayerInTurn();
                twoPlayerController.drawSlotPlayerInTurn();

                twoPlayersGameView.setVisible(true);

                break;
            case textFor4PlayerOption:

                numberOfPlayers = 4;
                controller.prepareTableFor( numberOfPlayers );

                FourPlayersGame fourPlayersGameView = new FourPlayersGame();

                FourPlayersController fourPlayerController = new FourPlayersController(fourPlayersGameView, controller.getTable()) ;

                fourPlayersGameView.setController( fourPlayerController );


                new FourPlayersGame().setVisible(true);

                break;
            case textFor6PlayerOption:

                numberOfPlayers = 6;
                controller.prepareTableFor( numberOfPlayers );

                new SixPlayersGame().setVisible(true);

                break;
        }
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenToAskForInitialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenToAskForInitialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenToAskForInitialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenToAskForInitialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( () -> new ScreenToAskForInitialData().setVisible(true) );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel welcomeMessage;
    private javax.swing.JLabel askForPlayersQuantityMessage;
    private javax.swing.JComboBox<String> playerQuantityList;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
